apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pesaloop-backend-staging
  namespace: argocd
  labels:
    project: pesaloop
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/francis-mwas/deployments.git
    targetRevision: main
    path: pesaloop/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: pesaloop-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
